friend_zone_rails/config/routes.rb
Rails.application.routes.draw do

  resources :backups

  resources :archives

  get 'users/login' => 'users#login'
  resources :users

  get 'playlists/lookup' => 'playlists#lookup'
  get 'playlists/deleteConfirm' => 'playlists#delete_confirm'
  resources :playlists do
    resources :songs, shallow: true
  end

  get '/' => 'users#login_page'

  get '/callback' => 'users#spotify_callback'

end

friend_zone_rails/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :user
  has_many :songs, dependent: :destroy
  has_many :archives, dependent: :destroy
end

friend_zone_rails/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
  end

  def lookup
    fz_playlist = Playlist.find_by(spotify_uri: params[:spotify_uri])
    if fz_playlist
      redirect_to fz_playlist
    end
    playlist_link = 'https://api.spotify.com/v1/users/' + params[:owner] + '/playlists/' + params[:spotify_uri]
    spotify_playlist_data = HTTParty.get(
        playlist_link,
        headers: {
          'Authorization' => 'Bearer ' + session[:access_token]
        }
      )
    @spotify_playlist = {
      name: spotify_playlist_data['name'],
      snapshot_id: spotify_playlist_data['snapshot_id'],
      spotify_uri: params[:spotify_uri],
      owner_id: params[:owner]
    }
    @songs = spotify_playlist_data['tracks']['items']

  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @fz_playlist = Playlist.find(params[:id])
    
    playlist_link = 'https://api.spotify.com/v1/users/' + @fz_playlist[:owner] + '/playlists/' + @fz_playlist[:spotify_uri]
    spotify_playlist_data = HTTParty.get(
        playlist_link,
        headers: {
          'Authorization' => 'Bearer ' + session[:access_token]
        }
      )
    @spotify_playlist = {
      name: spotify_playlist_data['name'],
      snapshot_id: spotify_playlist_data['snapshot_id'],
      spotify_uri: @fz_playlist[:spotify_uri],
      owner_id: @fz_playlist[:owner]
    }
    @songs = spotify_playlist_data['tracks']['items']
  end

  # GET /playlists/new
  def new
    playlist_link = 'https://api.spotify.com/v1/users/' + params[:owner] + '/playlists/' + params[:id]
    spotify_playlist_data = HTTParty.get(
        playlist_link,
        headers: {
          'Authorization' => 'Bearer ' + session[:access_token]
        }
      )
    @playlist = Playlist.new({
      spotify_uri: params[:id],
      snapshot_id: spotify_playlist_data['snapshot_id'],
      owner: params[:owner],
      repeats_allowed: false
    })
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    # need to use current user's id here to create the playlist
    new_playlist_data = playlist_params
    new_playlist_data[:user_id] = session[:user_id]
    @playlist = Playlist.new(new_playlist_data)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /playlists/deleteConfirm
  def delete_confirm
    @playlist = Playlist.find(params[:playlist_id])
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      format.html { redirect_to user_url(session[:user_id]), notice: 'Playlist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:spotify_uri, :snapshot_id, :collaboration_name, :owner, :repeats_allowed, :rolloff_frequency)
    end
end

friend_zone_rails/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

friend_zone_rails/app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spotify_uri %><br>
    <%= f.text_field :spotify_uri, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :snapshot_id %><br>
    <%= f.text_field :snapshot_id, :readonly => true %>
  </div>
  <div class="field">
    <%= f.label :collaboration_name %><br>
    <%= f.text_field :collaboration_name %>
  </div>
  <div class="field">
    <%= f.label :owner %><br>
    <%= f.text_field :owner, :readonly => true %>
  </div>

<!-- This should be used somewhere else, during radio station enroll -->
<!--   <p>How many days of history should we maintain?</p>
  <div class="field">
    <%= radio_button_tag(:rolloff_frequency, "fortyfive") %>
    <%= label_tag(:rolloff_frequency_fortyfive, "Archive songs added more than 45 days ago") %><br>
    <%= radio_button_tag(:rolloff_frequency, "thirty") %>
    <%= label_tag(:rolloff_frequency_thirty, "Archive songs added more than 30 days ago") %><br>
    <%= radio_button_tag(:rolloff_frequency, "fifteen") %>
    <%= label_tag(:rolloff_frequency_fifteen, "Archive songs added more than 15 days ago") %><br>
    <%= radio_button_tag(:rolloff_frequency, "none") %>
    <%= label_tag(:rolloff_frequency_none, "Don't automatically") %><br>
  </div>
  <p>Would you like to allow duplicated songs in this archive? If not, your archive will only contain one copy of any duplicate tracks.</p>
  <div class="field">
    <%= radio_button_tag(:repeats_allowed, "true") %>
    <%= label_tag(:repeats_allowed_true, "Duplicates are allowed") %><br>
    <%= radio_button_tag(:repeats_allowed, "false") %>
    <%= label_tag(:repeats_allowed_false, "Don't allow the same song to be added twice") %><br>
  </div> -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

friend_zone_rails/app/views/playlists/delete_confirm.html.erb
<h1>Are you sure you want to remove "<%= @playlist[:name] %>" from the Friend Zone?</h1>
<%= button_to 'STOP! I want to keep it!', @playlist, method: :get %><br>
<%= button_to 'Yes', @playlist, method: :delete, data: { confirm: 'Are you sure?' } %>

friend_zone_rails/app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

friend_zone_rails/app/views/playlists/index.html.erb
<h1>Listing playlists</h1>

<table>
  <thead>
    <tr>
      <th>Spotify uri</th>
      <th>Snapshot</th>
      <th>Collaboration name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.spotify_uri %></td>
        <td><%= playlist.snapshot_id %></td>
        <td><%= playlist.collaboration_name %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

friend_zone_rails/app/views/playlists/lookup.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @spotify_playlist[:name] %></h1>
<h4>Snapshot Id<%= @spotify_playlist[:snapshot_id] %></h4>


<!-- should probably just be a link_to -->
<%= link_to_unless(@fz_playlist, "Add this playlist to FZ tracking", { action: "new", id: @spotify_playlist[:spotify_uri], owner: @spotify_playlist[:owner_id] }) %>

<table>
  <tr>
    <th>Song Number</th>
    <th>Song Name</th>
  </tr>
  <% @songs.each_with_index do |song, idx| %>
    <tr>
      <td><%= idx + 1%></td>
      <td><%= song['track']['name'] %></td>
    </tr>
  <% end %>
</table>

friend_zone_rails/app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

friend_zone_rails/app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @spotify_playlist[:name] %></h1>
<h4>Snapshot Id<%= @spotify_playlist[:snapshot_id] %></h4>

<!-- should probably just be a link_to -->
<%= link_to_if(@fz_playlist, "Get this playlist outta the zone...(delete)", { action: "delete_confirm", playlist_id: @fz_playlist.id }) %>


<table>
  <tr>
    <th>Song Number</th>
    <th>Song Name</th>
  </tr>
  <% @songs.each_with_index do |song, idx| %>
    <tr>
      <td><%= idx + 1 %></td>
      <td><%= song['track']['name'] %></td>
    </tr>
  <% end %>
</table>