friend_zone_rails/config/routes.rb
Rails.application.routes.draw do

  resources :backups

  resources :archives

  get 'users/login' => 'users#login'
  resources :users

  get 'playlists/lookup' => 'playlists#lookup'
  get 'playlists/deleteConfirm' => 'playlists#delete_confirm'
  resources :playlists do
    resources :songs, shallow: true
  end

  get '/' => 'users#login_page'

  get '/callback' => 'users#spotify_callback'

end

friend_zone_rails/app/models/backup.rb
class Backup < ActiveRecord::Base
  belongs_to :playlist
  has_many :songs
end

friend_zone_rails/app/controllers/backups_controller.rb
class BackupsController < ApplicationController
  before_action :set_backup, only: [:show, :edit, :update, :destroy]

  # GET /backups
  # GET /backups.json
  def index
    @backups = Backup.all
  end

  # GET /backups/1
  # GET /backups/1.json
  def show
  end

  # GET /backups/new
  def new
    @backup = Backup.new
  end

  # GET /backups/1/edit
  def edit
  end

  # POST /backups
  # POST /backups.json
  def create
    @backup = Backup.new(backup_params)

    respond_to do |format|
      if @backup.save
        format.html { redirect_to @backup, notice: 'Backup was successfully created.' }
        format.json { render :show, status: :created, location: @backup }
      else
        format.html { render :new }
        format.json { render json: @backup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backups/1
  # PATCH/PUT /backups/1.json
  def update
    respond_to do |format|
      if @backup.update(backup_params)
        format.html { redirect_to @backup, notice: 'Backup was successfully updated.' }
        format.json { render :show, status: :ok, location: @backup }
      else
        format.html { render :edit }
        format.json { render json: @backup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backups/1
  # DELETE /backups/1.json
  def destroy
    @backup.destroy
    respond_to do |format|
      format.html { redirect_to backups_url, notice: 'Backup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backup
      @backup = Backup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backup_params
      params.require(:backup).permit(:name, :spotify_uri, :snapshot_id, :collaboration_name, :year, :month, :is_archive_backup)
    end
end

friend_zone_rails/app/helpers/backups_helper.rb
module BackupsHelper
end

friend_zone_rails/app/views/backups/_form.html.erb
<%= form_for(@backup) do |f| %>
  <% if @backup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@backup.errors.count, "error") %> prohibited this backup from being saved:</h2>

      <ul>
      <% @backup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :spotify_uri %><br>
    <%= f.text_field :spotify_uri %>
  </div>
  <div class="field">
    <%= f.label :snapshot_id %><br>
    <%= f.text_field :snapshot_id %>
  </div>
  <div class="field">
    <%= f.label :collaboration_name %><br>
    <%= f.text_field :collaboration_name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.text_field :month %>
  </div>
  <div class="field">
    <%= f.label :is_archive_backup %><br>
    <%= f.check_box :is_archive_backup %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

friend_zone_rails/app/views/backups/edit.html.erb
<h1>Editing backup</h1>

<%= render 'form' %>

<%= link_to 'Show', @backup %> |
<%= link_to 'Back', backups_path %>

friend_zone_rails/app/views/backups/index.html.erb
<h1>Listing backups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Spotify uri</th>
      <th>Snapshot</th>
      <th>Collaboration name</th>
      <th>Year</th>
      <th>Month</th>
      <th>Is archive backup</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backups.each do |backup| %>
      <tr>
        <td><%= backup.name %></td>
        <td><%= backup.spotify_uri %></td>
        <td><%= backup.snapshot_id %></td>
        <td><%= backup.collaboration_name %></td>
        <td><%= backup.year %></td>
        <td><%= backup.month %></td>
        <td><%= backup.is_archive_backup %></td>
        <td><%= link_to 'Show', backup %></td>
        <td><%= link_to 'Edit', edit_backup_path(backup) %></td>
        <td><%= link_to 'Destroy', backup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backup', new_backup_path %>

friend_zone_rails/app/views/backups/new.html.erb
<h1>New backup</h1>

<%= render 'form' %>

<%= link_to 'Back', backups_path %>

friend_zone_rails/app/views/backups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @backup.name %>
</p>

<p>
  <strong>Spotify uri:</strong>
  <%= @backup.spotify_uri %>
</p>

<p>
  <strong>Snapshot:</strong>
  <%= @backup.snapshot_id %>
</p>

<p>
  <strong>Collaboration name:</strong>
  <%= @backup.collaboration_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @backup.year %>
</p>

<p>
  <strong>Month:</strong>
  <%= @backup.month %>
</p>

<p>
  <strong>Is archive backup:</strong>
  <%= @backup.is_archive_backup %>
</p>

<%= link_to 'Edit', edit_backup_path(@backup) %> |
<%= link_to 'Back', backups_path %>